### ISSUE TITLE
Double-check client-side skill ranges

### ISSUE THREAD

**Issue by TwoLaid** [TitanRO/Issues#12] opened 2018-05-06 07:04 UTC
I have a small suspicion that the client-side skill ranges are not all completely correct. Here is why:

Sometimes when I want to use Firebolt while out of range, my character does not walk far enough to the enemy target to cast it. Firebolt has a range of 9. Here are the scenarios I've tested:

* Casting while just in range (9) works: `ExxxxxxxxM` (E=enemy, x=space, M=Mage)
* Casting while way out of range (12): `ExxxxxxxxxxxxM` will cause me to walk to range 9 and cast: `ExxxxxxxxM`
* Casting while just out of range (10): `ExxxxxxxxM` does absolutely nothing, no walking and no casting

I don't have another server/client to test so maybe this is standard behavior but I found it very annoying

**Comment by trojal** [comment] 2018-05-06 07:41
I feel like this might be the same as iRO, but I do recall someone fixing this at some point (maybe it was pserver code, though -- I should check MouRO code)

**Comment by trojal** [comment] 2018-05-06 20:06
http://ragnarok-server.com/index.php?/topic/72-casting-out-of-cast-range-only-walks-not-casts/

**Comment by trojal** [comment] 2018-05-25 10:06
Same kinda thing with Bash, casting out of range just makes the char walk up and not Bash the egg:
https://puu.sh/AsDOi/06278bb5f3.mp4

**Comment by Smokie123** [comment] 2018-05-26 00:17
can you fucking fix this already you clown

**Comment by Smokie123** [comment] 2018-05-26 15:21
Fucking fix this. It's an absolute cancer to use certain skills with this bug.
https://github.com/rathena/rathena/issues/1423
https://github.com/rathena/rathena/issues/2083
https://github.com/rathena/rathena/issues/2937

I am quite sure this issue is caused by something in skillinfolist.lub and skillinfo_f.lub

**Comment by timogasda** [comment] 2018-05-26 20:55
I've been also experiencing this with simple auto-attacks. As in: I am far
away from a mob, I click and hold the mob to order an attack, my character
walks up to the mob with 1 cell distance and doesnt attack.

**Comment by trojal** [comment] 2018-06-03 06:43
Fixed by GepardShield update. Confirmed that his latest version introduced this bug that he had previously fixed.

**Closed by trojal** 2018-06-03 06:43 UTC
